### PR TITLE
Update uploadme.sql

### PR DESCRIPTION
**Pull request by Brackzz**
I fixed the sql you would need to name it jakes blah blah now all they have to do is insert it into a database

### CODE REVIEW

**Comment by Itz-Hyperz** [comment]
You turned jakes good practices into bad practices 🤦🏻‍♂️ 

You removed all the comments explaining what things are doing 😂 
also, you added a footer to the bottom of a file which destroys anyone else's brand and rights to there brand by using this...

It is clear here you know nothing about what you're doing.

**Comment by FAXES** [comment]
Why remove the internal documentation explaining what functions are doing? This is good formatting. Especially for others that may not know their way around SQL.

Also, footer is useless.

I recommend the PR be closed as it serves no good use/intentions.

**Comment by Brackzz** [comment]
I edited it on my phone I am not done yet retard go kys

**Comment by Brackzz** [comment]
And ur both being retard everyone knows that they don't want there database to be named jakesblqhbal just removed that so you can select and import 🤦🤦🤦

**Pull request closed without merging**
